name: Run Unit Tests

# Workflow starts when receiving custom event sent by CI workflow
on: [push, pull_request]

permissions:
  security-events: write
  pull-requests: write
  actions: read
  contents: read
  issues: write

# Jobs to be executed
jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:

      # Push source to scratch org
      - name: "Push source to scratch org"
        run: sfdx force:source:push

      # Run Apex tests
      - name: "Run apex tests"
        run: sfdx force:apex:test:run
