name: Deploy and Test Salesforce Code

on:
  push:
    branches:
      - main
      - feature1
      # Add other branches here as needed
  pull_request:
    branches:
      - main
      - feature1
      # Add other branches here as needed
    types:
      - closed

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          curl -sL https://developer.salesforce.com/tools/sfdxcli-linux | bash

      # Authenticate with Salesforce
      - name: Authenticate with Salesforce
        run: |
          echo "Logging into Salesforce..."
          echo "sfdx force:auth:sfdxurl:store -f <(echo \"{\\\"instanceUrl\\\": \\\"https://efficiency-customizatio261-dev-ed.scratch.lightning.force.com\\\", \\\"accessToken\\\": \\\"6Cel800DO8000002OyDB888O80000004hw1Fahk2OXw9dM4WLGBG9n4FGsEZECGXEBvfbu3ik7LCcdOBwggJmDaAa2saUdcwCREQfEjazyU\\\"}\")"
          sfdx force:auth:sfdxurl:store -f <(echo "{\"instanceUrl\": \"https://efficiency-customizatio261-dev-ed.scratch.lightning.force.com\", \"accessToken\": \"6Cel800DO8000002OyDB888O80000004hw1Fahk2OXw9dM4WLGBG9n4FGsEZECGXEBvfbu3ik7LCcdOBwggJmDaAa2saUdcwCREQfEjazyU\"}")

      # Push source to Salesforce org
      - name: Push source to Salesforce org
        run: |
          echo "Deploying source to Salesforce org..."
          sfdx force:source:push

      # Run Apex tests
      - name: Run Apex tests
        run: |
          echo "Running Apex tests..."
          sfdx force:apex:test:run
